### ISSUE TITLE
for ++ fails to compile

### ISSUE THREAD

**Issue by alienself** [brendan-duncan/wgsl_reflect#13]
Hi,

Great library however there is an issue with for loops. 
The `i++` generates an error and prevents the reflection to happen.

```wgsl
fn foo() {
   for (var i = 0; i < 4; i++) {
   }
}
```

**Comment by brendan-duncan** [comment]
Thanks, I'll get that fixed shortly. increment operator was added fairly recently, I added the parsing for it, but didn't add the rule to the for loop incrementer.

**Comment by brendan-duncan** [comment]
Should be fixed now

**Comment by alienself** [comment]
Wow that was fast, amazing! Thanks for this fix!
