### ISSUE TITLE
Failed to handle numeric literals with suffix

### ISSUE THREAD

**Issue by bbbbx** [brendan-duncan/wgsl_reflect#33]
for example:

```wgsl
42i;
42u;
42f;
```

**Comment by brendan-duncan** [comment]
Should be fixed now from https://github.com/brendan-duncan/wgsl_reflect/commit/f24a37f8d0228973808a251999221e84b26616a7.

**Comment by bbbbx** [comment]
It seems that the edge case `0i` doesn't work
