### ISSUE TITLE
Bug: storage buffer resource missing from entry when writing only (no reading)

### ISSUE THREAD

**Issue by alienself** [brendan-duncan/wgsl_reflect#47]
Hello,

Amazing work on this library!  

I just discovered a little bug when using compute shaders with it:

When defining a `read_write` storage buffer and only writing to it in my compute shader, the buffer will not appear in the entry's resources of the program. However if I add read operation then the buffer does appear.

In the code below, only `particlesA` appears in the resources array of the compute program.

```wgsl
struct Particle {
  pos : vec2<f32>,
  vel : vec2<f32>,
}

struct Particles {
  particles : array<Particle>,
}

@binding(0) @group(0) var<storage, read> particlesA: Particles;
@binding(1) @group(0) var<storage, read_write> particlesB : Particles;

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) GlobalInvocationID : vec3<u32>) {
  var index = GlobalInvocationID.x;
  var vPos = particlesA.particles[index].pos;
  particlesB.particles[index].pos = vPos;
}
```

Adding a blank read operation (`var _ = particlesB.particles[index];`) will add the `particlesB` in the resources array:

```wgsl
struct Particle {
  pos : vec2<f32>,
  vel : vec2<f32>,
}

struct Particles {
  particles : array<Particle>,
}

@bind var<storage, read> particlesA: Particles;
@bind var<storage, read_write> particlesB : Particles;

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) GlobalInvocationID : vec3<u32>) {
  var index = GlobalInvocationID.x;
  var vPos = particlesA.particles[index].pos;

  var _ = particlesB.particles[index]; // <-- to enable particlesB in the resources of the shader

  particlesB.particles[index].pos = vPos;
}  
```

**Comment by brendan-duncan** [comment]
Thanks! I'll get this fixed up.

**Comment by brendan-duncan** [comment]
To be clear, when you say "the buffer will not appear in the entry's resources", what code are you doing to check that?

**Comment by brendan-duncan** [comment]
I pushed the fix for the first sample where particlesB is only assigned. Both particlesA and particlesB show up in the function resources list now.

**Comment by alienself** [comment]
That was fast, just tested it and it works perfectly! Thank you very much for this fix Brendan!

**Comment by brendan-duncan** [comment]
I had some long compiles for work today :-)
