### ISSUE TITLE
Documentation bug?

### ISSUE THREAD

**Issue by louderspace** [brendan-duncan/wgsl_reflect#55]
https://github.com/brendan-duncan/wgsl_reflect/blob/3efb215eb9a4087594f9bda049442178c6a0454e/README.md?plain=1#L251

`console.log(groups[0][1].size); // 108, the size of the uniform buffer.`

The code above doesn't seem correct.  Based on your readme, I wrote typescript based unit tests to verify the code and I'm getting 96, not 108.  Seems like a mat4x4<f32>+vec4<f32>+f32 = 64+16+4+12(extra padding) = 96.

[wgsl_reflect_unit_tests.txt](https://github.com/user-attachments/files/16629050/wgsl_reflect_unit_tests.txt)

**Comment by brendan-duncan** [comment]
Yeah, sorry for the typo. Fixed.

**Comment by louderspace** [comment]
One more!  

https://github.com/brendan-duncan/wgsl_reflect/blob/3efb215eb9a4087594f9bda049442178c6a0454e/README.md?plain=1#L307

a, b, c, d, e, f, g, h = 8
