### ISSUE TITLE
f16 based templates are incorrectly sized as f32s

### ISSUE THREAD

**Issue by louderspace** [brendan-duncan/wgsl_reflect#57]
Paste this snippet into https://brendan-duncan.github.io/wgsl_reflect/example.html

```
@binding(0) @group(0) var<uniform> a1: f16;            // This is correctly sized at 2 bytes!
@binding(0) @group(1) var<uniform> a2: vec2<f16>;      // This should be 4 bytes, not 8
@binding(0) @group(2) var<uniform> a3: vec3<f16>;      // This should be 6 bytes, not 12
@binding(0) @group(3) var<uniform> a4: vec4<f16>;      // This should be 8 bytes, not 16
@binding(0) @group(4) var<uniform> a5: mat2x2<f16>;    // This should be 8 bytes, not 16
@binding(0) @group(5) var<uniform> a6: mat2x3<f16>;    // This should be 16 bytes, not 32
@binding(0) @group(6) var<uniform> a7: mat2x4<f16>;    // This should be 16 bytes, not 32
@binding(0) @group(7) var<uniform> a8: mat3x2<f16>;    // This should be 12 bytes, not 24
@binding(0) @group(8) var<uniform> a9: mat3x3<f16>;    // This should be 24 bytes, not 48
@binding(0) @group(9) var<uniform> a10: mat3x4<f16>;   // This should be 24 bytes, not 48
@binding(0) @group(10) var<uniform> a11: mat4x2<f16>;  // This should be 16 bytes, not 32
@binding(0) @group(11) var<uniform> a11: mat4x3<f16>;  // This should be 32 bytes, not 64
@binding(0) @group(12) var<uniform> a11: mat4x4<f16>;  // This should be 32 bytes, not 64
```

As the comments indicate, it is my belief that these are incorrectly sized.  

Source reference:  https://www.w3.org/TR/WGSL/#alignment-and-size

**Comment by brendan-duncan** [comment]
Thanks for the report, you are correct, my vec and mat sizing code has some issues. I'll get it fixed up shortly.

**Comment by brendan-duncan** [comment]
That was an easy fix, I just had a typo when it was checking for f16. It's pushed to git, and added a test confirming your code is now calculating the correct sizes. I'll update npm after I get through my regular work (I had some time waiting for a compile).

**Comment by louderspace** [comment]
Fantastic!

**Comment by louderspace** [comment]
npm still shows 1.10 as the latest. 

https://www.npmjs.com/package/wgsl_reflect?activeTab=versions

**Comment by brendan-duncan** [comment]
Woops, new I forgot to do something. It's published as 1.0.12, because I switched over to my other computer and forgot to pull the git changes when I did the 1.0.11 publish, so I had to do it again as 1.0.12.

**Comment by louderspace** [comment]
<img src="https://media0.giphy.com/media/yGYViAYRbph2vBnjAI/giphy.gif"/>

**Comment by brendan-duncan** [comment]
Closing the issue. Let me know if you run into anything else.
