### ISSUE TITLE
++ and += not parsed

### ISSUE THREAD

**Issue by mighdoll** [brendan-duncan/wgsl_reflect#7]
e.g. 
```

fn foo() {
    var b = 1;
    b+=1;
    b++;
}
```

**Comment by brendan-duncan** [comment]
I'll get these added.

**Comment by brendan-duncan** [comment]
I pushed an update with the recent WGSL changes: ++, --, +=, -=, *=, /=, |=, &=, ^=, >>=, <<=, const, and static_assert.
